// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SportClient is the client API for Sport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SportClient interface {
	// ListSportEvents will return a collection of all sport events.
	ListSportEvents(ctx context.Context, in *ListSportEventsRequest, opts ...grpc.CallOption) (*ListSportEventsResponse, error)
}

type sportClient struct {
	cc grpc.ClientConnInterface
}

func NewSportClient(cc grpc.ClientConnInterface) SportClient {
	return &sportClient{cc}
}

func (c *sportClient) ListSportEvents(ctx context.Context, in *ListSportEventsRequest, opts ...grpc.CallOption) (*ListSportEventsResponse, error) {
	out := new(ListSportEventsResponse)
	err := c.cc.Invoke(ctx, "/sport.Sport/ListSportEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SportServer is the server API for Sport service.
// All implementations should embed UnimplementedSportServer
// for forward compatibility
type SportServer interface {
	// ListSportEvents will return a collection of all sport events.
	ListSportEvents(context.Context, *ListSportEventsRequest) (*ListSportEventsResponse, error)
}

// UnimplementedSportServer should be embedded to have forward compatible implementations.
type UnimplementedSportServer struct {
}

func (UnimplementedSportServer) ListSportEvents(context.Context, *ListSportEventsRequest) (*ListSportEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSportEvents not implemented")
}

// UnsafeSportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SportServer will
// result in compilation errors.
type UnsafeSportServer interface {
	mustEmbedUnimplementedSportServer()
}

func RegisterSportServer(s grpc.ServiceRegistrar, srv SportServer) {
	s.RegisterService(&Sport_ServiceDesc, srv)
}

func _Sport_ListSportEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSportEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportServer).ListSportEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sport.Sport/ListSportEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportServer).ListSportEvents(ctx, req.(*ListSportEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sport_ServiceDesc is the grpc.ServiceDesc for Sport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sport.Sport",
	HandlerType: (*SportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSportEvents",
			Handler:    _Sport_ListSportEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sport/sport.proto",
}
